### PR TITLE
Treatment option + comparison

### PR DESCRIPTION
**Pull request by zhongqi22**

### CODE REVIEW

**Comment by leon-sleepinglion** [comment]
Do you guys think the comparison table's outline is too subtle? maybe we can make it thicker to improve visibility.

**Comment by zhongqi22** [comment]
i will try to fix that


Regards,
Wang Zhong Qi
Undergraduate Computer Science Student
University of Malaya
kate.wang22@gmail.com / +60172886064

**Comment by zhongqi22** [comment]
i will try to fix that

**Comment by khaukheng** [comment]
Lol,animation suddenly work after merge pull request lol

**Comment by zhongqi22** [comment]
@khaukheng it works before i changed the table outline tho

**Pull request merged**
